In [2]:
import numpy as np 
print("numpy loaded successfully")

numpy loaded successfully


In [3]:
np.array(1)  # Output: array(1, 2, 3)
print(type(np.array(1)))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [4]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)  # Output: [[1 2 3 4 5]
              #          [6 7 8 9 10]]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [5]:
print(len(arr) ) # python function Output: 10

2


In [15]:
## attribute 
print(arr.shape) # Output: (10,)
print(arr.ndim) # Output: 1  dimension
print(arr.size) # Output: 10
print(arr.dtype)

(2, 5)
2
10
int64


In [7]:
# methods
print(np.arange(0,10)) # start, stop, step


[0 1 2 3 4 5 6 7 8 9]


In [8]:
np.random.rand(3,4)

array([[0.15996018, 0.43047997, 0.90474228, 0.27389068],
       [0.78182803, 0.66289818, 0.23554293, 0.23946205],
       [0.29969579, 0.71202418, 0.85311633, 0.70090997]])

In [9]:
np.random.randint(0,10,10)  # start, stop, size

array([0, 1, 2, 2, 7, 3, 1, 1, 0, 8], dtype=int32)

In [14]:
# zeros
np.zeros((2,4,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# min, max , argmax, argmin
print(arr)
arr.ravel()
arr=arr.flatten()

min(arr)  # py func
np.min(arr)  # np method  max 

# index finding
np.argmax(arr)   # argmin


[ 1  2  3  4  5  6  7  8  9 10]


np.int64(9)

In [28]:
# mean std
print(arr)
arr+arr    #3 add

list1=[1,2,3,4,5]
list1+list1     # concat

arr.mean()
arr.std()

[ 1  2  3  4  5  6  7  8  9 10]


np.float64(2.8722813232690143)