In [ ]:
import numpy as np 
print("numpy loaded successfully")

numpy loaded successfully


In [ ]:
np.array(1)  # Output: array(1, 2, 3)
print(type(np.array(1)))  # Output: <class 'numpy.ndarray'>

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [12]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)  # Output: [[1 2 3 4 5]
              #          [6 7 8 9 10]]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [13]:
print(len(arr) ) # python function Output: 10

2


In [ ]:
## attribute 
print(arr.shape) # Output: (10,)
print(arr.ndim) # Output: 1  dimension
print(arr.size) # Output: 10

(2, 5)
2
10


In [ ]:
# methods
print(np.arange(0,10)) # start, stop, step


[0 1 2 3 4 5 6 7 8 9]


In [18]:
np.random.rand(3,4)

array([[0.32394476, 0.84852919, 0.52100843, 0.71645694],
       [0.60768217, 0.9883185 , 0.54728667, 0.33913948],
       [0.03053545, 0.82515687, 0.1650905 , 0.47519699]])

In [ ]:
np.random.randint(0,10,10)  # start, stop, size

array([2, 6, 4, 4, 5, 9, 5, 0, 2, 2], dtype=int32)